### ISSUE TITLE
Calendar list incorrectly color

### ISSUE THREAD

**Issue by benmcnix** [conema/monterail-dark#12]
Hello again. I've noticed after a recent TB update (60.0b11) on Mac my Calendar is darkened by your theme where it previously was not (or maybe you did an update?). Either way, it now looks like this in my calendar list:
![calendar](https://user-images.githubusercontent.com/5635267/45309037-726da200-b4e8-11e8-980b-8d55b3572153.png)

I've blurred out some things because they contain personal information. But basically 5 of the 7 calendar names have a white row background with white font, so I can't see those unless I click on the calendar name and the background turns orange.

**Comment by conema** [comment]
Yep, with the new update the dark theme is applied to lightning too. Do you have the same issue with the activity tab on the right?

![immagine](https://user-images.githubusercontent.com/12801153/45309886-0fe6c700-b525-11e8-9888-12a784bcbbac.png)

**Comment by benmcnix** [comment]
Yes I do. The Events view shows the date with white letters on a light gray:
![calendar_and_1_reminder](https://user-images.githubusercontent.com/5635267/45312347-7651f200-b4f1-11e8-97b2-d193c60a4698.png)

And the Tasks view has a similar white on white problem as the calendar list:
![calendar_and_1_reminder](https://user-images.githubusercontent.com/5635267/45312378-8669d180-b4f1-11e8-85b3-90de04195ec4.png)

**Comment by conema** [comment]
Could you tell me if this resolve the issues with the light background in menus?
Installation is like the last time, sorry for the delay, but I'm really busy these days!
[chrome.zip](https://github.com/conema/monterail-dark/files/2368080/chrome.zip)

**Comment by pheraph** [comment]
I fixed this problem via userchrome.css with this naive approach:

```CSS
#calendar-task-tree-detail treechildren::-moz-tree-row(odd),
#calendar-list-tree-widget treechildren::-moz-tree-row(odd) {
  background: #3c3b37 !important;
}

#calendar-task-tree-detail treechildren::-moz-tree-row(even),
#calendar-list-tree-widget treechildren::-moz-tree-row(even) {
  background: #3c3b37 !important;
}
```

**Comment by conema** [comment]
> I fixed this problem via userchrome.css with this naive approach

Yes, that is the same fix that I put on the zip. Since you're on MacOs, could you try to fix the background issue in the calendar (see screenshot)? It's very difficult for me to debug the theme without a mac =(

![immagine](https://user-images.githubusercontent.com/12801153/45368032-e55b4380-b5e2-11e8-98cf-950ca5648464.png)

**Comment by conema** [comment]
Let me know if this works: [chrome.zip](https://github.com/conema/monterail-dark/files/2372326/chrome.zip)

**Comment by benmcnix** [comment]
Partially... The New Event bar is good, so just the bar above:
![calendar](https://user-images.githubusercontent.com/5635267/45384228-06b43380-b5d3-11e8-9bf9-0adc2b7fe50a.png)

**Comment by pheraph** [comment]
> Yes, that is the same fix that I put on the zip. Since you're on MacOs, could you try to fix the background issue in the calendar (see screenshot)? It's very difficult for me to debug the theme without a mac =(

This fixed it for me:

```CSS
#mini-day-box, #mini-day-box hbox {
  background: #3c3b37 !important;
}
```

<img width="217" alt="fix" src="https://user-images.githubusercontent.com/58503/45412686-98757c80-b677-11e8-9860-0e47f15ac483.png">
